// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nellojkfoiwqmuvouwsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lbGxvamtmb2l3cW11dm91d3N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTI2NjMsImV4cCI6MjA2Mzc4ODY2M30.1IQL2LotLACgSPmDCvTnX_f2VmaIWEEo6TQ5unuELVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);